name: deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  deployments: none

jobs:
  deploy-app:
    runs-on: ubuntu-22.04
    environment: Production
    timeout-minutes: 20
    permissions:
      packages: write
      id-token: write
    env:
      image_tag_app: ghcr.io/${{ github.repository }}/app:${{ github.sha }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Log in to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    
    - name: Build image
      run: |
        echo image_tag: ${{ env.image_tag_app }}
        docker build --tag ${{ env.image_tag_app }} ./src/someapi2/

    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@299cde98a08ff8b1c2bfde1e5a067bce67a6d2b8
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ env.image_tag_app }}

    - name: Docker push
      run: docker push ${{ env.image_tag_app }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ Secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ Secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ Secrets.AZURE_SUBSCRIPTION_ID }}

    - name: bicep-build-output
      uses: Azure/bicep-build-action@v1.0.1
      with:
        bicepFilePath: ./build/main.bicep
        outputFilePath: ./build/main.json

    - name: Run Snyk to check configuration files for security issues
      uses: snyk/actions/iac@299cde98a08ff8b1c2bfde1e5a067bce67a6d2b8
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        file: ./build/main.json

    - name: Deploy app
      uses: azure/arm-deploy@v1
      env:
        containerImage: ${{ env.image_tag_app }}
        revisionSuffix: ${{ github.sha }}
        location: 'norwayeast'
      with:
        scope: resourcegroup
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./build/main.bicep
        deploymentMode: Complete
        deploymentName: app-${{ github.sha }}
        parameters: 'location=${{ env.location }} containerImage=${{ env.containerImage }} revisionSuffix=${{ env.revisionSuffix }}'
